#!/bin/bash

rm -Rf docker-compose.yml
touch docker-compose.yml

DATABASE_URL=${DATABASE_URL:-mongodb://mongo}
DATABASE_NAME=${DATABASE_NAME:-databr}

echo "version: '2'
services:" >> docker-compose.yml

shopt -s globstar
for DIR in */; do
  if [ "$DIR" != "go_bot/" ]
  then
    empty=""
    bot="${DIR///$empty}"

    compose="
  $bot:
    build:
      context: ./$bot
      dockerfile: Dockerfile
    environment:
      - API_ROOT='http://api'
      - ENV='production'
      - PORT='80'
      - STATUSPAGEIO_ENABLE=false
      - DATABASE_URL=$DATABASE_URL
      - DATABASE_NAME=$DATABASE_NAME
      - MONGO_URL=$DATABASE_URL
      - MONGO_DATABASE_NAME=$DATABASE_NAME
      - PRIVATE_KEY=abc
      - MEMCACHED_URL=localhost:11211"
    echo "${compose}" >> docker-compose.yml
  fi
done
