#!/bin/bash


if which docker >/dev/null; then
    echo "Docker installed"
else

  apt-get update
  apt-get install apt-transport-https ca-certificates -y
  apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  rm -f /etc/apt/sources.list.d/docker.list
  echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' > /etc/apt/sources.list.d/docker.list
  apt-get update
  apt-get purge lxc-docker -y
  apt-cache policy docker-engine
  apt-get install docker-engine -y
  service docker start

fi


if [ -x /usr/local/bin/docker-compose ]; then
  echo "Docker Compose installed"
else
  curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
fi
